general:
  rosbag_directory: /home/forest_ws/src/stream_deck_controller/rosbags
  task_name: pick_cube_and_put_in_bowl

rosbag_topics:
  - /joint_states
  - /cartesian/solution
  - /dxl_input/pos_right
  - /dxl_input/gripper_right
  - /cartesian/gripper_right_grasping_frame/reference
  - /cartesian/gripper_right_grasping_frame/reach/goal
  - /camera/color/image_raw
  - /camera/color/compressed