general:
  rosbag_directory: /home/forest_ws/src/stream_deck_controller/rosbags
  task_name: pick_and_place

rosbag_topics:
  - /joint_states
  - /cartesian/solution
  - /mobile_base_controller/cmd_vel
  - /dxl_input/pos_right
  - /dxl_input/gripper_right
  - /gripper_right_grasping_frame/read
  - /gripper_right_grasping_frame/goal
  - /tiago_right_camera_color_optical_frame/pose
  - /tiago_head_camera_color_optical_frame/pose
  - /tiago_right_camera/color/image_raw
  - /tiago_right_camera/color/image_raw/compressed
  - /tiago_right_camera/color/camera_info
  - /tiago_right_camera/depth/image_raw
  - /tiago_right_camera/depth/image_raw/compressed
  - /tiago_right_camera/depth/image_raw/compressedDepth
  - /tiago_right_camera/depth/camera_info
  - /tiago_head_camera/color/image_raw
  - /tiago_head_camera/color/image_raw/compressed
  - /tiago_head_camera/color/camera_info
  - /tiago_head_camera/depth/image_raw
  - /tiago_head_camera/depth/image_raw/compressed
  - /tiago_head_camera/depth/image_raw/compressedDepth
  - /tiago_head_camera/depth/camera_info
  - /tiago_right_camera/color/image_raw/compressedDepth
  - /tiago_right_camera/color/image_raw/compressedDepth/compressed
  - /tiago_right_camera/color/image_raw/compressed/compressedDepth
